packages:
  - indy-vdr-*

catalog:
  "@biomejs/biome": 2.4.10
  "@types/node": ^20.12.11
  koffi: ^2.15.1
  rimraf: ^5.0.5
  typescript: ~5.4.5
  vite-tsconfig-paths: ^5.1.4
  vitest: ^4.0.12

ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "koffi"
